// src/routes/about/+page.svelte
<script>
	import TopHero from '../../component/TopHero.svelte';
</script>

<div class="flex flex-col space-y-9 text-center">
	<TopHero tag="about us" title="Who are we">
		Welcome to Cybergenix Security, your go-to partner for cutting-edge
		<br />
		cybersecurity solutions. We specialize in protecting your digital infrastructure
		<br />
		with advanced technology and expert strategies
	</TopHero>

	<div class="container mx-auto flex justify-around px-4">
		<div class="grid grid-cols-1 gap-16 md:grid-cols-2">
			<img
				src="https://static.wixstatic.com/media/f88665_714282c57cef431c8ec80de2da9c0c84~mv2.jpg/v1/fill/w_580,h_380,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/pexels-fauxels-3183197.jpg 1x, https://static.wixstatic.com/media/f88665_714282c57cef431c8ec80de2da9c0c84~mv2.jpg/v1/fill/w_1160,h_760,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/pexels-fauxels-3183197.jpg 2x"
				alt="About1"
				class="rounded-xl"
			/>
			<div class="md:text-left">
				<div class="mb-4 font-bold text-blue-300 uppercase">Our Mission</div>
				<div class="mb-4 text-4xl font-bold">Breaking Barriers in Cybersecurity</div>
				<p>
					Welcome to Cybergenix Security, where we are redefining the landscape of cybersecurity
					with a comprehensive and forward-thinking approach. Our mission is threefold: to protect
					the digital world from an ever-expanding array of cyber threats, to safeguard the future
					by equipping the next generation with critical cybersecurity skills, and to provide
					unparalleled consultancy services.
					<br />
					<br />
					At Cybergenix Security, we believe that securing today's digital environment is just the beginning.
					Our proactive measures and advanced technologies are designed to defend against current threats
					while anticipating future risks.
				</p>
			</div>
		</div>
	</div>
</div>

// src/app/about/page.tsx
'use client';

import TopHero from '@/components/TopHero';
import Image from 'next/image';

export default function About() {
  return (
    <main className="min-h-screen bg-gray-900 text-white">
      <div className="container mx-auto px-4 py-16">
        <div className="flex flex-col space-y-9 text-center">
          <TopHero title="About Us" tag="about">
            Learn more about Cybergenix Security and our mission to provide top-notch cybersecurity solutions.
          </TopHero>
        </div>

        <div className="mt-16 grid grid-cols-1 gap-8 md:grid-cols-2">
          <div className="space-y-6">
            <h2 className="text-3xl font-bold">Our Mission</h2>
            <p className="text-lg text-gray-300">
              At Cybergenix Security, we are dedicated to providing comprehensive cybersecurity solutions
              that protect your digital assets and ensure business continuity. Our mission is to make
              cybersecurity accessible and effective for businesses of all sizes.
            </p>
          </div>
          <div className="relative h-64 w-full overflow-hidden rounded-lg">
            <Image
              src="https://static.wixstatic.com/media/f88665_1234567890~mv2.jpg"
              alt="About Us"
              fill
              className="object-cover"
            />
          </div>
        </div>
      </div>
    </main>
  );
}
